<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-10F3EDE" failures="1" tests="3" name="Default test(failed)" time="16.301" errors="0" timestamp="2022-10-27T16:13:10 IST">
  <testcase classname="TestCases.FailedTestCases" name="verifyAppUrlTest" time="1.014">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestCases.FailedTestCases.verifyAppUrlTest() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestCases.FailedTestCases.verifyAppUrlTest() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyAppUrlTest -->
  <testcase classname="TestCases.FailedTestCases" name="verifyLoginByUrlTest" time="0.504"/>
  <testcase classname="TestCases.FailedTestCases" name="verifyLoginByTextTest" time="0.526"/>
  <testcase classname="TestCases.FailedTestCases" name="verifySwagLabsLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifySwagLabsLogoTest -->
  <testcase classname="TestCases.FailedTestCases" name="verifyAppTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAppTitleTest -->
  <testcase classname="TestCases.FailedTestCases" name="verifyLoginByLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyLoginByLogoTest -->
  <testcase classname="TestCases.FailedTestCases" name="verifyBigLogoTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyBigLogoTest -->
</testsuite> <!-- Default test(failed) -->
